package com.example.nativelauncher.ui.components

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.nativelauncher.model.AppInfo

@Composable
fun AppOptionsDialog(
    app: AppInfo,
        onDismiss: () -> Unit,
            onAppInfo: () -> Unit,
                onUninstall: () -> Unit
                ) {
                    AlertDialog(
                            onDismissRequest = onDismiss,
                                    title = { Text(text = app.label) },
                                            text = {
                                                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                                                                        Button(
                                                                                            onClick = {
                                                                                                                    onAppInfo()
                                                                                                                                            onDismiss()
                                                                                                                                                                },
                                                                                                                                                                                    modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                        Text("App-Informationen")
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        Button(
                                                                                                                                                                                                                                                                            onClick = {
                                                                                                                                                                                                                                                                                                    onUninstall()
                                                                                                                                                                                                                                                                                                                            onDismiss()
                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                    colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.error),
                                                                                                                                                                                                                                                                                                                                                                                        modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                                                                                                                                                                                                                                        ) {
                                                                                                                                                                                                                                                                                                                                                                                                                            Text("Deinstallieren")
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        confirmButton = {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dismissButton = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TextButton(onClick = onDismiss) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text("Abbrechen")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    