package com.example.nativelauncher.ui.screens

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.gestures.detectVerticalDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.unit.dp
import com.example.nativelauncher.ui.components.AppIconItem
import com.example.nativelauncher.ui.components.ClockWidget
import com.example.nativelauncher.viewmodel.LauncherScreen
import com.example.nativelauncher.viewmodel.LauncherViewModel

@OptIn(ExperimentalFoundationApi::class)
@Composable
fun HomeScreen(viewModel: LauncherViewModel) {
    val pagerState = rememberPagerState(pageCount = { 2 })

        Box(
                modifier = Modifier
                            .fillMaxSize()
                                        .pointerInput(Unit) {
                                                        detectVerticalDragGestures { _, dragAmount ->
                                                                            if (dragAmount < -30) {
                                                                                                    viewModel.currentScreen = LauncherScreen.DRAWER
                                                                                                                        }
                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                        ) {
                                                                                                                                                                Column(
                                                                                                                                                                            modifier = Modifier
                                                                                                                                                                                            .fillMaxSize()
                                                                                                                                                                                                            .statusBarsPadding()
                                                                                                                                                                                                                            .navigationBarsPadding(),
                                                                                                                                                                                                                                        horizontalAlignment = Alignment.CenterHorizontally
                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                            Row(
                                                                                                                                                                                                                                                                            modifier = Modifier
                                                                                                                                                                                                                                                                                                .fillMaxWidth()
                                                                                                                                                                                                                                                                                                                    .padding(16.dp),
                                                                                                                                                                                                                                                                                                                                    horizontalArrangement = Arrangement.End
                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                IconButton(onClick = { viewModel.currentScreen = LauncherScreen.SETTINGS }) {
                                                                                                                                                                                                                                                                                                                                                                                    Icon(
                                                                                                                                                                                                                                                                                                                                                                                                            imageVector = Icons.Default.Settings,
                                                                                                                                                                                                                                                                                                                                                                                                                                    contentDescription = "Einstellungen",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            tint = Color.White
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Spacer(modifier = Modifier.height(40.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ClockWidget()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Spacer(modifier = Modifier.weight(1f))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            HorizontalPager(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state = pagerState,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .fillMaxWidth()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .height(260.dp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) { page ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val pinnedApps = if (page == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    viewModel.installedApps.take(viewModel.gridColumnsState)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        viewModel.installedApps.drop(viewModel.gridColumnsState).take(viewModel.gridColumnsState)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LazyVerticalGrid(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            columns = GridCells.Fixed(viewModel.gridColumnsState),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                modifier = Modifier.fillMaxSize(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    contentPadding = PaddingValues(16.dp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        items(pinnedApps) { app ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AppIconItem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app = app,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        showLabel = viewModel.showLabelsState,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    iconSizeDp = viewModel.iconSizeState,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick = { viewModel.launchApp(app) },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onLongClick = { viewModel.selectedAppForMenu = app }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                