package com.example.nativelauncher.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.nativelauncher.viewmodel.LauncherScreen
import com.example.nativelauncher.viewmodel.LauncherViewModel

@Composable
fun SettingsScreen(viewModel: LauncherViewModel) {
    Column(
            modifier = Modifier
                        .fillMaxSize()
                                    .background(Color(0xFF121212))
                                                .statusBarsPadding()
                                                            .navigationBarsPadding()
                                                                        .padding(16.dp)
                                                                            ) {
                                                                                    Row(
                                                                                                verticalAlignment = Alignment.CenterVertically,
                                                                                                            modifier = Modifier.fillMaxWidth()
                                                                                                                    ) {
                                                                                                                                IconButton(onClick = { viewModel.currentScreen = LauncherScreen.HOME }) {
                                                                                                                                                Icon(
                                                                                                                                                                    imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                                                                                                                                                                                        contentDescription = "Zurück",
                                                                                                                                                                                                            tint = Color.White
                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    Spacer(modifier = Modifier.width(8.dp))
                                                                                                                                                                                                                                                                Text("Launcher Einstellungen", fontSize = 20.sp, color = Color.White)
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                Spacer(modifier = Modifier.height(24.dp))

                                                                                                                                                                                                                                                                                        Text("Rasterspalten: ${viewModel.gridColumnsState}", color = Color.White)
                                                                                                                                                                                                                                                                                                Slider(
                                                                                                                                                                                                                                                                                                            value = viewModel.gridColumnsState.toFloat(),
                                                                                                                                                                                                                                                                                                                        onValueChange = { viewModel.updateGridColumns(it.toInt()) },
                                                                                                                                                                                                                                                                                                                                    valueRange = 3f..6f,
                                                                                                                                                                                                                                                                                                                                                steps = 2
                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                Spacer(modifier = Modifier.height(16.dp))

                                                                                                                                                                                                                                                                                                                                                                        Text("Icon-Größe: ${viewModel.iconSizeState} dp", color = Color.White)
                                                                                                                                                                                                                                                                                                                                                                                Slider(
                                                                                                                                                                                                                                                                                                                                                                                            value = viewModel.iconSizeState.toFloat(),
                                                                                                                                                                                                                                                                                                                                                                                                        onValueChange = { viewModel.updateIconSize(it.toInt()) },
                                                                                                                                                                                                                                                                                                                                                                                                                    valueRange = 40f..72f,
                                                                                                                                                                                                                                                                                                                                                                                                                                steps = 4
                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                Spacer(modifier = Modifier.height(16.dp))

                                                                                                                                                                                                                                                                                                                                                                                                                                                        Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    modifier = Modifier.fillMaxWidth(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                horizontalArrangement = Arrangement.SpaceBetween,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            verticalAlignment = Alignment.CenterVertically
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text("App-Namen anzeigen", color = Color.White)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Switch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            checked = viewModel.showLabelsState,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onCheckedChange = { viewModel.updateShowLabels(it) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Spacer(modifier = Modifier.height(16.dp))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier.fillMaxWidth(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        horizontalArrangement = Arrangement.SpaceBetween,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    verticalAlignment = Alignment.CenterVertically
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text("Erzwungener Dark Mode", color = Color.White)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Switch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    checked = viewModel.isDarkModeState,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onCheckedChange = { viewModel.updateDarkMode(it) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            